#!/usr/bin/env python3
"""Emit cloudflare/seed_attention.sql from the live pool (attention items + decision records only).
These rows are small and safe as SQL. The large blob feeds are loaded separately by
scripts/seed_docs.py (bound-parameter PUTs — D1 caps a single SQL statement's size).

    python3 scripts/seed_d1.py [/path/to/data]
    npx wrangler d1 execute hm-command-center --remote --file cloudflare/seed_attention.sql
"""
import glob, json, os, sys

def find_pool(argv):
    if len(argv) > 1 and os.path.isdir(argv[1]): return argv[1]
    for pat in ("/sessions/*/mnt/*/data", "/sessions/*/mnt/Host Modern/data",
                os.path.expanduser("~/Library/CloudStorage/*/Shared drives/Host Modern/Claude/Host Modern/data")):
        for p in sorted(glob.glob(pat)):
            if os.path.isfile(os.path.join(p, "ecomm_state.json")): return p
    sys.exit("could not locate the data pool; pass it as an argument")

def q(s): return "'" + str(s).replace("'", "''") + "'"

def main():
    pool = find_pool(sys.argv)
    out = ["-- generated by scripts/seed_d1.py — DO NOT COMMIT (runtime data)",
           "BEGIN TRANSACTION;", "DELETE FROM attention_items; DELETE FROM attention_decisions;"]
    nitem = nrec = 0
    idir = os.path.join(pool, "attention", "items")
    files = sorted(glob.glob(os.path.join(idir, "*.json")))
    if not files:
        qp = os.path.join(pool, "attention", "queue.json")
        items = json.load(open(qp, encoding="utf-8")).get("items", []) if os.path.isfile(qp) else []
    else:
        items = []
        for fp in files:
            try: items.append(json.load(open(fp, encoding="utf-8")))
            except Exception: pass
    for it in items:
        iid = it.get("item_id")
        if not iid: continue
        out.append("INSERT INTO attention_items(item_id,owner,generated_at,item_json,updated_at) "
                   f"VALUES({q(iid)},{q(it.get('owner'))},{q(it.get('generated_at'))},{q(json.dumps(it,ensure_ascii=False))},{q('seed')});")
        nitem += 1
    for fp in sorted(glob.glob(os.path.join(pool, "attention", "decisions", "*.json"))):
        try: rec = json.load(open(fp, encoding="utf-8"))
        except Exception: continue
        if not rec.get("item_id"): continue
        rec.setdefault("ts", "")
        out.append("INSERT INTO attention_decisions(item_id,ts,record_json) "
                   f"VALUES({q(rec['item_id'])},{q(rec.get('ts'))},{q(json.dumps(rec,ensure_ascii=False))});")
        nrec += 1
    out.append("COMMIT;")
    dst = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "cloudflare", "seed_attention.sql")
    open(dst, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"pool={pool}\nwrote {dst}  items={nitem}  decisions={nrec}")

if __name__ == "__main__": main()
